name: Cypress Tests
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2' 
      - run: npm ci
      - name: Install Java
        run: apt-get update && apt-get install -y curl wget openjdk-11-jdk
      - name: set JAVA_HOME
        run: export JAVA_HOME=$JAVA_HOME:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
      - name: Make possible generate reports
        run: chmod -R o+xw allure-results
      - name: get users
        run: cat .
      - name: Generate Report
        if: always()
        run: npm run allure:generate